feat: se agrega el workflow que valide que los commits cumplen con los requisitos

diff --git a/.github/workflows/test_unitarios.yml b/.github/workflows/test_unitarios.yml
--- a/.github/workflows/test_unitarios.yml
+++ b/.github/workflows/test_unitarios.yml
@@ -12,12 +12,37 @@ on:
         default: ""
 
 jobs:
+
   run-tests:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout repo
         uses: actions/checkout@v4
+
+      - name: Validate commit messages in PR
+        if: github.event_name == 'pull_request'
+        run: |
+          ALLOWED_REGEX="^(feat|fix|hotfix|bugfix|breakingchange)(\(|!|\:)"
+          INVALID_COMMIT_MSGS=""
+
+          # Obtiene los SHAs de los commits en el PR
+          COMMITS=$(git log origin/${GITHUB_BASE_REF}..HEAD --pretty=format:"%H")
+
+          for sha in $COMMITS; do
+            MSG=$(git log -1 --pretty=format:"%s" $sha)
+            if [[ ! $MSG =~ $ALLOWED_REGEX ]]; then
+              INVALID_COMMIT_MSGS="$INVALID_COMMIT_MSGS\n - $sha: $MSG"
+            fi
+          done
+
+          if [ -n "$INVALID_COMMIT_MSGS" ]; then
+            echo "❌ Los siguientes commits tienen mensajes inválidos y deben empezar con uno de feat, fix, hotfix, bugfix, breakingchange:"
+            echo -e "$INVALID_COMMIT_MSGS"
+            exit 1
+          else
+            echo "✅ Todos los commits del PR tienen prefijo válido."
+          fi
 
       - name: Set up Python
         uses: actions/setup-python@v5
