fix: se ajusta test para que guarde el reporte aunque unos de lso test falle

diff --git a/.github/workflows/test_unitarios.yml b/.github/workflows/test_unitarios.yml
--- a/.github/workflows/test_unitarios.yml
+++ b/.github/workflows/test_unitarios.yml
@@ -102,13 +102,16 @@ jobs:
           done
           echo "========================================="
           
-          if [ $STATUS -ne 0 ]; then
-            echo "Some services did not meet the minimum 70% coverage requirement."
-            exit 1
-          fi
+          echo "::set-output name=failed::$STATUS"
 
       - name: Upload coverage reports as artifact
         uses: actions/upload-artifact@v4
         with:
           name: coverage-reports
           path: coverage-reports/
+
+      - name: Fail if coverage check did not pass
+        if: steps.coverage.outputs.failed != '0'
+        run: |
+          echo "Some services did not meet the minimum 70% coverage requirement."
+          exit 1
